#!/bin/bash

#Instalador
#El log se hace en el archivo instalep.log en el directorio /dirconf
#Creo el archivo de log
touch ./dirconf/instalep.log
ACTUALPATH=$(realpath ./)
#Funcion para escribir en consola y grabar en el log en una sola linea.
function echoes {
	echo "$1"
	echo "$1">> ./dirconf/instalep.log
}

# Devuelve verdadero si el parametro es igual del nombre reservado dirconf
function userInputIsInvalid() {

	if [ "$userInput" == "$reservedName" ]
	then
		return "1"
	else
		return "0"
	fi

}

#Funcion para la carga de nombres de carpetas.
function userInput(){

	echo "Defina el directorio de $2 ($ACTUALPATH/$1):"
	read userInput

	#Verifico que el input sea distinto del nombre reservado
	userInputIsInvalid userInput
	is_invalid=$?

	while [ "$is_invalid" == "1" ]
	do
		echo "ERROR: El nombre dirconf esta reservado."
		echo "Defina el directorio de $2 ($ACTUALPATH/$1):"
		read userInput
		userInputIsInvalid userInput
		is_invalid=$?
	
	done

	#Si el usuario ingresa un string vacio (apreta enter) dejo el valor por defecto.
	if [ $userInput ] 
	then 
		funcOutput=$userInput
	else
		funcOutput=$1
	fi

}

#Defino variables para guardar los nombres de los directorios
DIRCONF="dirconf"
DIRBIN="bin"
DIRMAE="mae"
DIRREC="nov"
DIROK="ok"
DIRPROC="imp"
DIRINFO="rep"
DIRLOG="log"
DIRNOK="nok"

INSTALLATIONOK=false

while [ "$INSTALLATIONOK" != true ]
do
#Mostrar y grabar "Inicio del proceso. Usuario Fecha y Hora"
DATE=$(date)
echoes "Inicio del proceso. $USER $DATE"

#Detectar si el sistema esta instalado. Para eso se chequea si existe el
#archivo instalep.conf en dirconf
if [ -f ./dirconf/instalep.conf ]
then
	#Mostrar y grabar todos los datos de instalacion (nombres de directorio)
	echoes 'Sistema instalado'
	old_IFS=$IFS
	IFS=$'\n'
	IFS=$old_IFS
	echoes "Directorio de Configuracion: ($ACTUALPATH/dirconf)"
        echoes "Directorio de Ejecutables: ($(cat ./dirconf/instalep.conf | grep DIRBIN= | awk -F '=' '{print$2}'))"
        ls "$(cat ./dirconf/instalep.conf | grep DIRBIN= | awk -F '=' '{print$2}')"
        echoes "Directorio de Maestros y Tablas: ($(cat ./dirconf/instalep.conf | grep DIRMAE= | awk -F '=' '{print$2}'))"
        ls "$(cat ./dirconf/instalep.conf | grep DIRMAE= | awk -F '=' '{print$2}')"
        echoes "Directorio de Recepcion de Novedades: ($(cat ./dirconf/instalep.conf | grep DIRREC= | awk -F '=' '{print$2}'))"
        echoes "Directorio de Archivos Aceptados: ($(cat ./dirconf/instalep.conf | grep DIROK= | awk -F '=' '{print$2}'))"
	echoes "Directorio de Archivos Procesados: ($(cat ./dirconf/instalep.conf | grep DIRPROC= | awk -F '=' '{print$2}'))"
	echoes "Directorio de Archivos de Reportes: ($(cat ./dirconf/instalep.conf | grep DIRINFO= | awk -F '=' '{print$2}'))"
	echoes "Directorio de Archivos de Log: ($(cat ./dirconf/instalep.conf | grep DIRLOG= | awk -F '=' '{print$2}'))"
	echoes "Directorio de Archivos Rechazados: ($(cat ./dirconf/instalep.conf | grep DIRNOK= | awk -F '=' '{print$2}'))"
	exit 0
fi


clear

#Comienza el ingreso de nombres de directorios
#Variables auxiliares --------------------------------------------------
userInput=""
reservedName="dirconf"
is_invalid="0"
funcOutput=""
# BIN --------------------------------------------------------------------------

userInput $DIRBIN "ejecutables"
DIRBIN=$funcOutput

# MAE --------------------------------------------------------------------------

userInput $DIRMAE "maestros y tablas"
DIRMAE=$funcOutput

# REC --------------------------------------------------------------------------

userInput $DIRREC "recepcion de novedades"
DIRREC=$funcOutput

# OK ---------------------------------------------------------------------------

userInput $DIROK "archivos aceptados"
DIROK=$funcOutput

# PROC -------------------------------------------------------------------------

userInput $DIRPROC "archivos procesados"
DIRPROC=$funcOutput

# INFO -------------------------------------------------------------------------

userInput $DIRINFO "reportes"
DIRINFO=$funcOutput

# LOG --------------------------------------------------------------------------

userInput $DIRLOG "log"
DIRLOG=$funcOutput

# NOK --------------------------------------------------------------------------

userInput $DIRNOK "rechazados"
DIRNOK=$funcOutput

# ------------------------------------------------------------------------------

#Obtengo el espacio libre en MBytes con una M al final.
FREESPACE=$(df ./ -BM |tail -1|awk '{print $4}')
#Le saco el ultimo caracter (M) para que quede el numero limpio.
FREESPACE=${FREESPACE%?}

#CORRECTSPACE es falsa mientras no se defina un espacio requerido correcto.
CORRECTSPACE=false
while [ "$CORRECTSPACE" != true ]
do
	echoes 'Defina espacio minimo libre para la repecion de archivos en Mbytes (100):'
	read SPACE

	if [ $SPACE -le $FREESPACE ] #less or equal
	then
		echoes 'Suficiente espacio en disco.'
		echoes "Espacio disponible: $FREESPACE Mb."
		echoes "Espacio requerido $SPACE Mb."
		echoes 'De enter para continuar'
		CORRECTSPACE=true
		read TECLA
	else
		echoes 'Insuficiente espacio en disco.'
		echoes "Espacio disponible: $FREESPACE Mb."
		echoes "Espacio requerido $SPACE Mb."
		echoes 'Intentelo nuevamente.'
	fi
done

#limpio pantalla
clear

#Muestro y grabo configuracion final y archivos.
echoes "Directorio de Configuracion: $ACTUALPATH/$DIRCONF"
#ls $DIRCONF
#ls $DIRCONF >> ./dirconf/instalep.log
echoes "Directorio de Ejecutables: $ACTUALPATH/$DIRBIN"
#ls $DIRBIN
#ls $DIRBIN >> ./dirconf/instalep.log
echoes "Directorio de Maestros y Tablas: $ACTUALPATH/$DIRMAE"
#ls $DIRMAE
#ls $DIRMAE >> ./dirconf/instalep.log
echoes "Directorio de Recepcion de Novedades: $ACTUALPATH/$DIRREC"
#ls $DIRREC
#ls $DIRREC >> ./dirconf/instalep.log
echoes "Directorio de Archivos Aceptados: $ACTUALPATH/$DIROK"
#ls $DIROK
#ls $DIROK >> ./dirconf/instalep.log
echoes "Directorio de Archivos Procesados: $ACTUALPATH/$DIRPROC"
#ls $DIRPROC
#ls $DIRPROC >> ./dirconf/instalep.log
echoes "Directorio de Archivos de Reportes: $ACTUALPATH/$DIRINFO"
#ls $DIRINFO
#ls $DIRINFO >> ./dirconf/instalep.log
echoes "Directorio de Archivos de Log: $ACTUALPATH/$DIRLOG"
#ls $DIRLOG
#ls $DIRLOG >> ./dirconf/instalep.log
echoes "Directorio de Archivos Rechazados: $ACTUALPATH/$DIRNOK"
#ls $DIRNOK
#ls $DIRNOK >> ./dirconf/instalep.log
echoes "Estado de la instalacion: LISTA"
echoes "Desea continuar con la instalacion? (Si - No)"

RESPONSE=""
while [ "$RESPONSE" != "Si" ] && [ "$RESPONSE" != "si" ] && [ "$RESPONSE" != "SI" ] && [ "$RESPONSE" != "No" ] && [ "$RESPONSE" != "NO" ] && [ "$RESPONSE" != "no" ]
do
	if [ "$RESPONSE" != "" ]
	then	
		echo "Debe ingresar Si o No.."
	fi
	read RESPONSE

	case "$RESPONSE" in
		Si|si|SI ) INSTALLATIONOK=true;;
	esac
done

done

echoes "Iniciando instalacion. Esta Ud. seguro? (Si - No)"

RESPONSE=""
while [ "$RESPONSE" != "Si" ] && [ "$RESPONSE" != "si" ] && [ "$RESPONSE" != "SI" ] && [ "$RESPONSE" != "No" ] && [ "$RESPONSE" != "NO" ] && [ "$RESPONSE" != "no" ]
do
	if [ "$RESPONSE" != "" ]
	then	
		echo "Debe ingresar Si o No.."
	fi	
	read RESPONSE

	case "$RESPONSE" in
		NO|no|No )	exit 0 ;;
	esac
done

#Creo los directorios
echoes "Creando Estructuras de directorio. . . ."
mkdir -p $DIRBIN
mkdir -p $DIRMAE
mkdir -p $DIRREC
mkdir -p $DIROK
mkdir -p $DIRPROC
mkdir -p "$DIRPROC/proc"
mkdir -p $DIRINFO
mkdir -p $DIRLOG
mkdir -p $DIRNOK

#Mover programas y funciones
echoes "Instalando Programas y Funciones"
DIRECTORIOBINARIOS="./paraMoverABin"
for file in "$DIRECTORIOBINARIOS"/*
do
  cp $file $DIRBIN
done

#Mover los archivos maestros y tablas
echoes "Instalando Archivos Maestros y Tablas"
DIRECTORIODATOS="./datos"
for file in "$DIRECTORIODATOS"/*
do
  cp $file $DIRMAE
done

# Grabo en el archivo instalep.conf en /dirconf un registro por cada variable
# configurada
# Primero los nombres de los directorios en el orden en el que son solicitados
# y luego un registro con el espacio requerido solicitado.
touch ./dirconf/instalep.conf
ACTUALDATE=$(date +"%d/%m/%Y %T")
cd dirconf
echo "DIRBIN=$DIRBIN=$USER=$ACTUALDATE" >> instalep.conf
echo "DIRMAE=$DIRMAE=$USER=$ACTUALDATE" >> instalep.conf
echo "DIRREC=$DIRREC=$USER=$ACTUALDATE" >> instalep.conf
echo "DIROK=$DIROK=$USER=$ACTUALDATE" >> instalep.conf
echo "DIRPROC=$DIRPROC=$USER=$ACTUALDATE" >> instalep.conf
echo "DIRINFO=$DIRINFO=$USER=$ACTUALDATE" >> instalep.conf
echo "DIRLOG=$DIRLOG=$USER=$ACTUALDATE" >> instalep.conf
echo "DIRNOK=$DIRNOK=$USER=$ACTUALDATE" >> instalep.conf
echo "GRUPO=$ACTUALPATH=$USER=$ACTUALDATE" >> instalep.conf
echo "DIRSPACE=$SPACE=$USER=$ACTUALDATE" >> instalep.conf
cd ..

echoes "Actualizando la configuracion del sistema"
echoes "Instalacion CONCLUIDA."

DATE=$(date)
echoes "Fin del proceso. $USER $DATE "
