#!/bin/bash

source ./logep

movep() {
	##Logeo en el log del comando o en movep si no me pasan ninguno
	LOGGER=$3
	if [ $# -eq 2 ]
	then
		LOGGER="movep"
	fi
	if [ ${1%/*} == $2 ]
	then
		logep -e $LOGGER "El origen y el destino son iguales"
		return
	fi 
	if [ ! -f $1 ]
	then
		logep -e $LOGGER "El archivo de origen no existe"
		return
	fi
	if [ ! -d $2 ]
	then
		logep -e $LOGGER "La carpeta destino no existe"
		return
	fi
	##Me quedo con el nombre del archivo
	FILENAME=${1##*/}
	##Reservo la carpeta dpl para guardar los duplicados en destino
	DUPLICATED="dpl"
	COUNT=1
	##Me paro sobre la carpeta destino y chequeo que no exita el archivo
	cd "$2"
	if [ ! -f $FILENAME ]
	then 	
		$(mv "$1" "$2")
	else
		##Si ya existe la carpeta dpl itero hasta que no encuentre el archivo con repeticiones 
		if [ -d $DUPLICATED ]
		then
			cd $DUPLICATED
			while [ -f "$FILENAME.$COUNT" ]
			do
				COUNT=$((COUNT+1))
			done
			$(mv "$1" "$2$DUPLICATED/$FILENAME.$COUNT")
		else
			mkdir $DUPLICATED
			$(mv "$1" "$2$DUPLICATED/$FILENAME.$COUNT")
		fi
	fi
}
