#!/bin/bash
source ./logep

#su primer parametro es una lista de los permisos a fijar, por ejemplo r w x
#sus siguientes parametros son los archivos a los cuales se les debe fijar los permisos
fijar_permisos () {
	for ((i=2; i<=$#; i++)) {
		for permiso in $1
		do
			eval archivo=\${$i}
			if [ ! -$permiso "$archivo" ]
			then
				if ! chmod -f +$permiso "$archivo"
				then 
					case $permiso in
						r) permiso=lectura;;
						x) permiso=ejecución;;
					esac
					printf "error, fallo al intentar fijar permiso de $permiso en archivo "$2", verificar si archivo ">&2
					printf "%s\n" "existe o si el usuario tiene permitido cambiar permisos">&2
					return -1
				fi
			fi
		done
	}
	return 0
}

#busco archivo configuracion, se que el directorio dirconf esta dentro de un directorio ancestro mio (recordar el usario puede meter a bin dentro de otro #directorio). Voy a mover hacia arriba por el arbol de directorios hasta encontrarlo
directorio_act="`pwd`"
while ! [ -a dirconf ]
do
	cd ..
done

configuracion="`pwd`/dirconf/instalep.conf"


cd "$directorio_act"

#me fijo si el ambiente ya fue inicalizado, para eso, uso la variable SETEPLAM como flag
if [ "$SETEPLAM" == SET ]
then
	mensaje="Ambiente ya inicializado, para reinicializar termine la sesión e ingrese nuevamente"
	printf "%s\n" "$mensaje">&2
	logep -e "initep" "$mensaje"

#Verifico permiso de los archivos configuracion y de los binarios
#Termina la ejecucion de initep sino puede cambiar el permiso correspondiente

elif fijar_permisos r "$configuracion" && fijar_permisos "r x" logep demonep movep listep.pl procep
then
	#Inicializo variables de directorio
	while read -r linea
	do
		nombreDirectorio=$( echo "$linea" | cut -d= -f1)
		ruta=$( echo "$linea" | cut -d= -f2)
		usuario=$(echo "$linea" | cut -d= -f3)
		case $nombreDirectorio in
			DIRBIN) 
				export DIRBIN=$ruta
				;;
			DIRMAE)
				export DIRMAE=$ruta
				;;
			DIRREC)
				export DIRREC=$ruta
				;;
			DIROK) 
				export DIROK=$ruta 
				;;
			DIRINFO)
				export DIRINFO=$ruta 
				;;
			DIRLOG)
				export DIRLOG=$ruta 
				;;
			GRUPO) 
				export GRUPO=$ruta 
				;;
			DIRPROC)
				export DIRPROC=$ruta 
				;;
			DIRNOK)
				export DIRNOK=$ruta 
				;;
		esac
	done <"$configuracion"
	
	#permisos de archivos maestros (los agrego aca porque necesito la ruta que se carga en DIRMAE)
	#supongo que todos los archivos maestros finalizan en .csv
	directorio_actual="$PWD"
	cd "$GRUPO/$DIRMAE"

	if fijar_permisos r *.csv
	then

		#en la variable de ambiente path agrego el directorio de ejecutables
		PATH=$PATH:"$GRUPO/$DIRBIN"

		#las variables se han inicalizado y los permisos de los arhcivos han sido fijados
		mensaje="Estado del Sistema: INICIALIZADO"
		printf "%s\n" "$mensaje"
		logep -i "initep" "$mensaje"

		#Pregunto por demonep
		read -p "¿Desea efectuar la activación de Demonep (S/N)?" opcion

		instrucciones_activar_demonio="Para activar el demonio corra comando demonep en background\n. Recibe como entrada los archivo maestros, tablas y el archivo novedades. Estos archivos se pueden encontrar en los directorios mae y rec respectivamente"

		instrucciones_desactivar_demonio="Para desactivar demonio use el comando kill SIGTERM pid, donde pid es identificador del proceso, en caso de fallar use kill SIGKILL pid."

		case "$opcion" in
			s|S ) 
				printf "%s\n" "$instrucciones_desactivar_demonio"
				logep -i "initep" "¿Desea efectuar la activación de Demonep (S/N)? Si"
				./demonep &
				pid=$!			
				printf "%s\n" "Demonep corriendo bajo el numero: $pid" 
				logep -i "initep" "Demonep corriendo bajo el numero: $pid"
				;;

			n|N ) 
				printf "%s\n" "$instrucciones_activar_demonio"
				printf "%s\n" "$instrucciones_desactivar_demonio"
				logep -i "initep" "¿Desea efectuar la activación de Demonep (S/N)? No"
				;;

			* ) 
				printf "Opción inválida\n">&2;&
		esac
		#no hubo problemas si llego hasta aqui asi que fijo SETEPLAM
		SETEPLAM=SET
	else
		#si hubo un error, limpio el ambiente borrando todas las variables incluyendo SETEPLAM
		#lo hago porque seria raro que saliera un mensaje de error y las variables quedaran inicializadas. El usario no confiaria en ellas.
		variables="SETEPLAM DIRBIN DIRMAE DIRRECK DIROCK DIRINFO DIRLOG GRUPO DIRPROC"
		for variable in $variables
		do
			unset "$variable"
		done
	fi
fi

cd "$directorio_actual"

